server:
  port: 8080
logging:
  level:
    org.springframework.validation: INFO
    org.hibernate: INFO
    org.springframework.http: DEBUG


spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: update  # Use 'create' if you don't want it to drop on shutdown
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
